#
# Makefile for i386-specific kdb files..
#
#  Copyright 1999, Silicon Graphics Inc.
# 
#  Written April 1999 by Scott Lurndal at Silicon Graphics, Inc.
#

SUB_DIRS     :=
MOD_SUB_DIRS := $(SUB_DIRS)
ALL_SUB_DIRS := $(SUB_DIRS)

#O_TARGET     := kdbm_vm.o

M_OBJS       := kdbm_vm.o kdbm_jfs.o

include $(TOPDIR)/Rules.make
